# Build settings
markdown: redcarpet
plugins:
  - jemoji
  - jekyll-picture-tag
  - jekyll-paginate
  - jekyll-livereload
  - jekyll-plantuml
  - jekyll_figure

# Site settings
title: "Comanche Hill"
description: > # this means to ignore newlines until "baseurl:"
  The personal blog of Mark Morga.

email: markmorga@gmail.com
#blog logo
logo: "/assets/images/comanche-hill.png"
# blog cover
cover: "/assets/images/bear-window-trail-big-bend.jpg"

name: 'Mark Morga'
author: 'Mark Morga'
author_image: "/assets/images/author-bw.jpg"

paginate: 5

url: "http://markmorga.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/mmorga
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://www.facebook.com/markmorga
    desc: Connect with me on facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/mmorga
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	google-plus
    url:	https://plus.google.com/+MarkMorga
    desc:	Add me on google+
    share_url:
    share_title:
    share_link:

exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - LICENSE.md
  - markmorga.sublime-project
  - markmorga.sublime-workspace
  - README.md
  - static
  - Rakefile
  - Gruntfile.js
  - package.json
  - node_modules
  - TODO.md

keep_files:
  - apple-touch-icon-114x114.png
  - apple-touch-icon-120x120.png
  - apple-touch-icon-144x144.png
  - apple-touch-icon-152x152.png
  - apple-touch-icon-180x180.png
  - apple-touch-icon-57x57.png
  - apple-touch-icon-60x60.png
  - apple-touch-icon-72x72.png
  - apple-touch-icon-76x76.png
  - apple-touch-icon-precomposed.png
  - apple-touch-icon.png
  - browserconfig.xml
  - CNAME
  - favicon-160x160.png
  - favicon-16x16.png
  - favicon-192x192.png
  - favicon-32x32.png
  - favicon-96x96.png
  - favicon.ico
  - mstile-144x144.png
  - mstile-150x150.png
  - mstile-310x150.png
  - mstile-310x310.png
  - mstile-70x70.png
  - .git

defaults:
  -
    scope:
      path: ""
    values:
      author: "Mark Morga"
      layout: "post"
      comments: true

redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - autolink
    - strikethrough
    - lax_spacing
    - superscript
    - smart

picture:
  source: "assets"
  output: "generated"
  markup: "picture"
  presets:
    default:
      ppi: [1, 1.5]
      attr:
        itemprop: "image"
      source_medium:
        media: "(min-width: 40em)"
        width: "600"
      source_default:
        width: "210"
    right:
      ppi: [1, 1.5]
      attr:
        itemprop: "image"
        class: "img-float-right"
      source_medium:
        media: "(min-width: 40em)"
        width: "600"
      source_default:
        width: "210"
    left:
      ppi: [1, 1.5]
      attr:
        itemprop: "image"
        class: "img-float-left"
      source_medium:
        media: "(min-width: 40em)"
        width: "600"
      source_default:
        width: "210"

sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/feed/index.xml"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"

# Server Config options
livereload: true     # You no longer need to include --livereload
# reload_port: 5678    # If you don't want to use the default port
