# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

# Site settings
title: "Comanche Hill"
description: > # this means to ignore newlines until "baseurl:"
  The personal blog of Mark Morga.

email: markmorga@gmail.com
#blog logo
logo: "/assets/images/mm_logo.jpg"
# blog cover
cover: "/assets/images/bear-window-trail-big-bend.jpg"

name: 'Mark Morga'
author: 'Mark Morga'
author_image: "/assets/images/author.jpg"

paginate: 5

url: "http://markmorga.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/mmorga
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://www.facebook.com/markmorga
    desc: Connect with me on facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/mmorga
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	google-plus
    url:	https://plus.google.com/+MarkMorga
    desc:	Add me on google+
    share_url:
    share_title:
    share_link:

defaults:
  -
    values:
      author: "Mark Morga"
