---
layout: post
title: Letus35 Mini Review
tags: []
status: publish
type: post
published: true
meta: {}
---
I've been wanting to get back into filmmaking.  I've been working periodically on a feature length script but in the meantime, I was asked to work on a music video (more on this soon).  The <a href="http://www.adapterplace.com/component/page,shop.product_details/flypage,shop.garden_flypage/product_id,43/category_id,11/manufacturer_id,0/option,com_virtuemart/Itemid,56/vmcchk,1/">Letus35 mini</a> has had me interested for quite a while.  I had made a deal with myself that I would purchase one if I made enough progress on the script, but the opportunity to shake it out on a music video was too tempting.

This summer, I purchased a <a href="http://www.usa.canon.com/consumer/controller?act=ModelInfoAct&fcategoryid=177&modelid=16186">Canon HF10 HDV camcorder</a>.  I had been looking at the HV20 and HV30, but the reviews indicated that the sensor quality on the HF10 was similar and I couldn't pass up the opportunity to leave tape behind.  So this post is more of a collection of my experiences with the combination of the HF10 and the Letus35 mini rather than a comprehensive review.

I chose to go with the Canon FD lens mount because I already had a few FD lenses and FD lenses are plentiful and inexpensive on eBay.  The Canon EF mount is also available, but due to the lack of aperture ring on EF lenses, you need to set the aperture via a fairly hacky process involving an EOS body, not the best way to work.  In practice, this may not be as bad as it sounds, because you have a tendency to want to use the lenses close to wide open anyway to get the shallow depth of field that is one of the prime features of this sort of adapter.

I ordered the kit which included the FD mount, the rails system to mount the camcorder and lens securely and a nice case.  After working with the adapter for a few days, I'm convinced the rails kit is a requirement.  The rails from Letus are high quality and I wouldn't feel comfortable using the adapter without the extra support that the rails provide.  The weak link in this system is definitely the filter threads that are used to join the camcorder to the adapter - you don't want to risk damaging them.

The setup of the system is a little involved, but with practice I believe I'll be able to assemble, align, and focus the system in about 15 minutes.  The focus process is pretty easy to accomplish, but the HF10's screen is too small to be used to focus on the ground glass.  Using the A/V out to my old standard-def TV was sufficient to focus correctly.  Since you will need to accomplish focus each time you re-assemble the system, you will probably want to bring a portable monitor with you on location.

My first feature request is for transport of the system.  It would be nice to have a case in which you could securely store the assembled system.  I will likely purchase one in the near future.  As an alternative, it would be nice to be able to leave the 37mm threaded ring on the camcorder when storing the adapter, but there isn't a cover to protect the adapter if you do this, so you end up having to fully disassemble the adapter when putting any part of it back in the case. 

When the HF10 is mounted on the riser on the rails system, the camcorder is pretty close to the power button on the adapter.  I thought this might be a problem at first, but in practice it wasn't at all.  The only potential problem here is that you can't immediately see if the power light is on.  I did forget once or twice to power the adapter on (which results in video with noticeable grain from the ground glass), but this is more a matter of practice and habit.  It's pretty obvious when the power is on because of the vibration of the unit.

Vibration is probably the biggest issue to be aware of.  Vibration is used by the adapter to hide the grain of the ground glass.  This works very well in practice.  I noticed a couple of side-effects with this system.  The biggest problem with the vibration is that it confuses the image stabilization system on the HF10.  With IS enabled, the video warbles when the camera is still and tends to overreact to actual shake.  As a result, I don't believe I'll be able to use the IS setting while using the adapter.  Not the end of the world.  The vibration does emit sound.  I doubt this sound would be picked up when using an external mic, but the on-board mics do pick up the sound as a low frequency buzz or rumble.  As a practical matter, if you are going to spend $1500 on a lens adapter system and not use an external mic, you hard larger problems ahead of you anyway.

The only other issue I ran into was a result of moving the camera around quite a bit on my camera test expedition with the kids.  Because the camera is mounted via the filter threads, the camera can easily rotate a bit with respect to the adapter during normal handling.  As a result, it's important to occasionally verify the alignment when shooting.  It only caused a problem for me when I was zoomed out more than I normally would be to accentuate the natural vignetting of my 24mm lens.  I didn't notice the alignment problem on the built in screen because of the vignetting, but I could see an off-kilter box frame in the final video.  This isn't a huge problem, but it is something to keep an eye on.

So aside from the minor issues (and they are truly minor), I'm really happy with the result.  The video I've captured looks much more filmic than I've ever achieved with pro-sumer cameras that I've had access to.  The look of the video straight off the camera is very pleasant to look at (nice bokeh from those FD lenses).  The focus is very manageable in the field with the built-in camcorder screen (the focus flaws in my camera test are more indicative of my skill than flaws in the adapter).  Certainly having a larger screen from the camcorder would make it easier to be much more precise when focusing.  I will be bringing a small monitor with me on shoots where I won't be running all over.

My biggest gripe in shooting on video in the past has that I haven't had control over the depth of field and now I do.  I'm a very happy adapter owner.  I'll post a followup with the results and lessons I learned on the music video shoot.  
